config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :messages

  map.resources :linkcategories

  map.resources :links,  :collection =>  { :list => :get }

  map.resources :categories

 
  map.resources :users

  map.resource :session

  map.resources :pages

  map.logout '/logout', :controller => 'sessions',:action => 'destroy'
  map.login   'login',    :controller =>  'sessions',:action => 'new'

 
  map.view_page ':name',:controller => 'viewer' , :action => 'show'

  

  map.root :controller => "viewer",:action => "show", :name => 'home'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_and_belongs_to_many :photos
   
end

app/models/contact_mailer.rb
class ContactMailer < ActionMailer::Base
  

  def message(message )
    subject    message.subject
    recipients  CONTACT_RECIPIENT
    from      message.email
    sent_on    Time.now
    
    body       :message => message
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
       has_and_belongs_to_many :linkcategorys
       validates_presence_of :title
end

app/models/linkcategory.rb
class Linkcategory < ActiveRecord::Base
        has_and_belongs_to_many :links
        validates_presence_of :title
        

end

app/models/message.rb
class Message < ActiveRecord::Base
    validates_presence_of :name, :subject,:body
    validates_format_of :email, :with => /^(\S+)@(\S+).(\S+)$/
    
end

app/models/page.rb
class Page < ActiveRecord::Base
  acts_as_textiled :body
  has_many :subpages , :class_name => 'Page', :foreign_key => 'parent_id'
  belongs_to :parent,:class_name => 'Page',:foreign_key => 'parent_id'

  def self.find_main
    Page.find(:all,:conditions => ['parent_id IS NULL'], :order => 'position')
  end
  def self.find_main_public 
    Page.find(:all, :conditions => ["parent_id IS NULL and admin != ?",true],:order => 'position')
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
 #  set_primary_key "created_at" 
    has_many :slides 
    has_and_belongs_to_many :categories 
    validates_presence_of :filename 
end

app/models/slide.rb
class Slide < ActiveRecord::Base
   belongs_to :slideshow   
   belongs_to :photo 
end

app/models/slideshow.rb
class Slideshow < ActiveRecord::Base
   has_many :slides 
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  # Virtual attribute for the unencrypted password
  attr_accessor :password

  validates_presence_of     :login, :email
  validates_presence_of     :password,                   :if => :password_required?
  validates_presence_of     :password_confirmation,      :if => :password_required?
  validates_length_of       :password, :within => 4..40, :if => :password_required?
  validates_confirmation_of :password,                   :if => :password_required?
  validates_length_of       :login,    :within => 3..40
  validates_length_of       :email,    :within => 3..100
  validates_uniqueness_of   :login, :email, :case_sensitive => false
  before_save :encrypt_password
  
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :password, :password_confirmation

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login, password)
    u = find_by_login(login) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    crypted_password == encrypt(password)
  end

  def remember_token?
    remember_token_expires_at && Time.now.utc < remember_token_expires_at 
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 2.weeks
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token            = encrypt("#{email}--#{remember_token_expires_at}")
    save(false)
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(false)
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  protected
    # before filter 
    def encrypt_password
      return if password.blank?
      self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{login}--") if new_record?
      self.crypted_password = encrypt(password)
    end
      
    def password_required?
      crypted_password.blank? || !password.blank?
    end
    
    
end

app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
    helper :all # include all helpers, all the time

    # See ActionController::RequestForgeryProtection for details Uncomment the
    # :secret if you're not using the cookie session store
    protect_from_forgery # :secret => '93b960b50d38ba686e6a44156074c2d5'
    include AuthenticatedSystem
  
    before_filter :get_pages_for_tabs
  
    def get_pages_for_tabs
        if:logged_in?
            @tabs = Page.find_main
        else
            @tabs = Page.find_main_public
        end
    end
    
    def get_page_metadata
      @page = Page.find_by_name(params[:name])
      @pagetitle = @page.title
    end  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_filter :login_required, :except => [:list]
    
  # GET /links
  # GET /links.xml
  def index
    @links = Link.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @links }
    end
  end

  def list
      @categories = Linkcategory.find(:all, :order => 'title')
     get_page_metadata
  end
  # GET /links/1
  # GET /links/1.xml
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/new
  # GET /links/new.xml
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.xml
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        flash[:notice] = 'Link was successfully created.'
        format.html { redirect_to(@link) }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        flash[:notice] = 'Link was successfully updated.'
        format.html { redirect_to(@link) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vid_helper.rb
module VidHelper
end

app/helpers/viewer_helper.rb
module ViewerHelper
end

app/views/links/edit.html.erb
<h1>Editing link</h1>

<% form_for(@link) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
     <b> Category </b> <br />
     <%= f.collection_select :linkcategory_ids, Linkcategory.find(:all, :order =>'title' ), :id,:title,{},:multiple => true %>
   </p>
  
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Description</th>
  </tr>

<% for link in @links %>
  <tr>
    <td><%=h link.url %></td>
    <td><%=h link.title %></td>
    <td><%=h link.description %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New link', new_link_path %>

app/views/links/list.html.erb
<h1>  Resources </h1>
<% for category in @categories %>
    <% unless category.links.empty? %>
        <h2> <%=h category.title %> </h2>
        <p> <%= category.description %> </p>
        <ul>  
          <% for link in category.links %>
              <li> <%= link_to link.title,link.url %> </li>
          <% end %>
        </ul>
    <% end %>
<% end %>

app/views/links/new.html.erb
<h1>New link</h1>

<% form_for(@link) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  
   <p>
     <b> Category </b> <br />
     <%= f.collection_select :linkcategory_ids, Linkcategory.find(:all, :order =>'title' ), :id,:title,{},:multiple => true %>
   </p>
  
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p>
  <b>Url:</b>
  <%=h @link.url %>
</p>

<p>
  <b>Title:</b>
  <%=h @link.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @link.description %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>